import { error } from '@sveltejs/kit';
import type { RequestHandler } from './$types.js';
import { getPb } from '$lib/pb.server.js';

export const GET: RequestHandler = async ({ params }) => {
	// Backup names are generated by PocketBase (or by us: yield_backup_<ts>.zip).
	if (!/^[\w.-]+\.zip$/.test(params.name)) {
		throw error(400, 'Invalid backup name');
	}

	const pb = await getPb();

	// Get a short-lived file access token and build the download URL
	const token = await pb.files.getToken();
	const url = pb.backups.getDownloadUrl(token, params.name);

	// Proxy the file through the SvelteKit server so the PocketBase URL
	// is never exposed to the client.
	const upstream = await fetch(url);
	if (!upstream.ok) {
		throw error(upstream.status === 404 ? 404 : 502, 'Backup download failed');
	}

	return new Response(upstream.body, {
		headers: {
			'Content-Type': upstream.headers.get('Content-Type') ?? 'application/zip',
			'Content-Disposition': `attachment; filename="${params.name}"`,
			...(upstream.headers.get('Content-Length')
				? { 'Content-Length': upstream.headers.get('Content-Length')! }
				: {})
		}
	});
};
